name: MyWorkflows

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]


jobs:
  print_Message_on_ubuntu:
    runs-on: ubuntu-latest

    
    steps:

      - uses: actions/setup-python@v3

      # Runs a single command using the runners shell
      - name: Run a python file
        run: python pythondemo.py
#         working-directory: ./sc/mainscript/run.py
        working-directory: ./scripts
